{
  "comments": [
    {
      "key": {
        "uuid": "da33351e_fce1e92a",
        "filename": "nfvbench/traffic_client.py",
        "patchSetId": 2
      },
      "lineNbr": 636,
      "author": {
        "id": 5807
      },
      "writtenOn": "2017-09-26T19:17:00Z",
      "side": 1,
      "message": "normally you don\u0027t pass the exception, the logging library will automatically attach the current exception to the message.\ninstead you should pass an error message that describes the situation (e.g. something like \"Got exception from traffic generator during binary search\"",
      "revId": "874f054afcd26f1562406e87d5943fabdfe1d34b",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da33351e_bcc2c182",
        "filename": "nfvbench/traffic_client.py",
        "patchSetId": 2
      },
      "lineNbr": 636,
      "author": {
        "id": 6949
      },
      "writtenOn": "2017-09-26T19:26:29Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "da33351e_fce1e92a",
      "revId": "874f054afcd26f1562406e87d5943fabdfe1d34b",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}